### ISSUE TITLE
Support Video Playlist

### ISSUE THREAD

**Issue by leocaseiro** [bobbywalters/webvtt#1]
Hi @bobbywalters. thanks for this amazing plugin, I was wondering if you would like to enable the cc button for playlists as well. In my WP, I can see my subtitles if I add the media, but not for video playlists(the same media).

Thank you.

> Update
> 
> I've tried to implement that using the `post_playlist` filter, but I realised that we will need to use JavaScript for that.
> 
> I'm going to focus on it later. If you'd like to give a try, I found this solution that might work for webvtt: https://www.iandevlin.com/blog/2015/02/javascript/dynamically-adding-text-tracks-to-html5-video

**Comment by bobbywalters** [comment]
Hey @leocaseiro that's a good idea, thanks for the suggestion. I've actually not used the playlist shortcode before but browsing over the code it seems possible. Yeah, by the looks of the handling there will need to be some JavaScript to add the track data in.

Thanks for the feedback and I'll get to work on it.

**Comment by bobbywalters** [comment]
Hey @leocaseiro, pushed v1.3.0 into the repository which adds support for the `[playlist]` shortcode. Please check it out when you get a chance.

**Comment by leocaseiro** [comment]
Hi @bobbywalters, 

You ae really a legend! Thank you so much for doing that.

I've just tried now! I'm going to test deeply and I'll let you know.

I had some issues with PHP side, I believe my server it's quite old, so I could not use `empty()` combined with calls inside conditionals. I'll send you a PR when I'm done with some fixes.

Few bugs to report, but I'm trying to fix myself. I need to test in a fresh WP setup first.
- I don't know why my playlist now is duplicated. It can be another plugin conflict though
- I noticed that the first movie at the list doesn't load with subtitles at the first time. You have to click into his own title or another one to see the [cc]  button.
- Somethings I have duplicates subtitles while changing between movies

I'll get back with better analysis and some fix tonight.
Cheers mate!

**Comment by bobbywalters** [comment]
Hey @leocaseiro, I updated how `empty()` was called so there's no conflict on versions prior to PHP 5.5. A small fix release is out v1.3.2 with those changes.

Regarding the duplicates and missing subtitles on the first video prior during loading, I tried out some more extensive testing and so far I haven't seen any of that behavior. For my testing I setup a page with 2 `[playlist]`s using the same 3 videos in a different order (to maximize the risk of duplicate handling). One video had a chapters track with 2 subtitles, a second video had 2 subtitles, and the final video didn't have any VTTs.

I looked for:
- The VTTs were properly loaded on the first video.
- The selected language was preserved across videos when switching to another video in the playlist.
- The selected language of one playlist didn't impact another; one playlist I selected Spanish subtitles and the other I had English selected. Both played, paused, and switched without interfering with the other playlist.
- There were not duplicate subtitles or chapters in either of the playlists.
- The `wp-playlist.min.js` from WebVTT was being loaded and only loaded once.
- Both editing and normal viewing of the post/page with 2 playlists worked as listed above.

With that in mind, perhaps the previous `empty()` usage was causing ripple effects and things didn't load up properly as that would have thrown some exceptions and interrupted the flow. Another scenario might be some page caching that needed to get cleared out once the new version of WebVTT was installed. However, the `empty()` causing the issues is more likely I think.

Please let me know how the changes to v1.3.2 work out.

**Comment by leocaseiro** [comment]
Hi @bobbywalters, it's all working really nice now!

I found out the duplicate items were from another plugin I created myself to add the "speed" into `mediaelement.js`. After disabling that plugin, it's working perfectly!

Many, many thanks for that! It's really easy and works great.
